#!/usr/bin/env python

import sys
from pathlib import Path
import os
import shutil


test_dir = Path(__file__).parent.parent / "tests" / "code"
file = sys.argv[1]
code = test_dir/ os.path.basename(file)
shutil.copy(code, file)
